#!/usr/bin/env python3
"""
Generate docker-compose.50node.yml with all 50 nodes defined.

This script creates a complete Docker Compose configuration for:
- 3 Bootstrap nodes (discovery)
- 5 Aggregator nodes (ML parameter servers)
- 40 Worker nodes (ML training)
- 2 GUI client nodes (testing)

Usage:
    python scripts/generate_50node_compose.py > docker/docker-compose.50node.yml
"""

HEADER = """# =============================================================================
# Docker Compose - 50-Node Hyper-Scale Test Environment (Mandate 3)
# =============================================================================
# AUTO-GENERATED - DO NOT EDIT MANUALLY
# Generated by: scripts/generate_50node_compose.py
#
# Sets up a 50-node mesh network for comprehensive E2E testing including:
# - 3 Bootstrap nodes for network discovery
# - 5 Aggregator/Parameter Server nodes for ML coordination
# - 40 Worker nodes for distributed ML training
# - 2 GUI client nodes for testing
#
# Network: 172.30.0.0/24
# IP Range: 172.30.0.10 - 172.30.0.75
#
# Usage:
#   docker-compose -f docker-compose.50node.yml up -d
#   docker-compose -f docker-compose.50node.yml ps
#   docker-compose -f docker-compose.50node.yml logs -f worker1
#   docker-compose -f docker-compose.50node.yml down
#
# Test Scenarios (Mandate 3):
#   1. Tor Communication: Test --use-tor flag between arbitrary nodes
#   2. Ephemeral Chat: Start chat session with encryption
#   3. ML Training: Distribute dataset to 40 workers, aggregate gradients
#   4. Fault Tolerance: Kill 5 random workers, verify continued operation
# =============================================================================

version: "3.8"

services:
"""

BOOTSTRAP_TEMPLATE = """
  bootstrap{id}:
    build:
      context: ../go
      dockerfile: Dockerfile
    container_name: wgt-bootstrap{id}
    hostname: bootstrap{id}
    command: >
      ./go-node 
      -node-id={node_id} 
      -capnp-addr=:8080 
      -libp2p=true 
      -libp2p-port={p2p_port}
      -mdns=true
      -local
    ports:
      - "{external_port}:8080"
      - "{p2p_port}:{p2p_port}"
    networks:
      wgt-mesh:
        ipv4_address: {ip_addr}
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - GO_NODE_ROLE=bootstrap
"""

AGGREGATOR_TEMPLATE = """
  aggregator{id}:
    build:
      context: ../go
      dockerfile: Dockerfile
    container_name: wgt-aggregator{id}
    hostname: aggregator{id}
    command: >
      ./go-node 
      -node-id={node_id} 
      -capnp-addr=:8080 
      -libp2p=true 
      -libp2p-port={p2p_port}
      -mdns=true
      -local
    ports:
      - "{external_port}:8080"
      - "{p2p_port}:{p2p_port}"
    networks:
      wgt-mesh:
        ipv4_address: {ip_addr}
    depends_on:
      - bootstrap1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - RUST_LOG=info
      - GO_NODE_ROLE=aggregator
      - ML_AGGREGATION_METHOD=fedavg
      - ML_MIN_WORKERS=30
"""

WORKER_TEMPLATE = """
  worker{id}:
    build:
      context: ../go
      dockerfile: Dockerfile
    container_name: wgt-worker{id}
    hostname: worker{id}
    command: >
      ./go-node 
      -node-id={node_id} 
      -capnp-addr=:8080 
      -libp2p=true 
      -libp2p-port={p2p_port}
      -mdns=true
      -local
    networks:
      wgt-mesh:
        ipv4_address: {ip_addr}
    depends_on:
      - bootstrap1
      - aggregator1
    environment:
      - RUST_LOG=warn
      - GO_NODE_ROLE=worker
"""

GUI_TEMPLATE = """
  gui-client{id}:
    build:
      context: ../
      dockerfile: docker/Dockerfile.python-gui
    container_name: wgt-gui-client{id}
    hostname: gui-client{id}
    ports:
      - "{external_port}:8080"
      - "{vnc_port}:5900"
    networks:
      wgt-mesh:
        ipv4_address: {ip_addr}
    depends_on:
      - bootstrap1
      - bootstrap2
    environment:
      - DISPLAY=:0
      - GO_NODE_HOST=bootstrap{bootstrap_id}
      - GO_NODE_PORT=8080
"""

NETWORK_CONFIG = """
networks:
  wgt-mesh:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
"""

def generate_bootstrap_nodes(count=3):
    """Generate bootstrap nodes configuration."""
    nodes = []
    for i in range(1, count + 1):
        node = BOOTSTRAP_TEMPLATE.format(
            id=i,
            node_id=i,
            external_port=8080 + i,
            p2p_port=9080 + i,
            ip_addr=f"172.30.0.{9 + i}"
        )
        nodes.append(node)
    return nodes

def generate_aggregator_nodes(count=5):
    """Generate aggregator/parameter server nodes configuration."""
    nodes = []
    for i in range(1, count + 1):
        node = AGGREGATOR_TEMPLATE.format(
            id=i,
            node_id=100 + i,
            external_port=8100 + i,
            p2p_port=9100 + i,
            ip_addr=f"172.30.0.{19 + i}"
        )
        nodes.append(node)
    return nodes

def generate_worker_nodes(count=40):
    """Generate worker nodes configuration."""
    nodes = []
    for i in range(1, count + 1):
        node = WORKER_TEMPLATE.format(
            id=i,
            node_id=200 + i,
            p2p_port=9200 + i,
            ip_addr=f"172.30.0.{29 + i}"
        )
        nodes.append(node)
    return nodes

def generate_gui_nodes(count=2):
    """Generate GUI client nodes configuration."""
    nodes = []
    for i in range(1, count + 1):
        node = GUI_TEMPLATE.format(
            id=i,
            external_port=8200 + i,
            vnc_port=5900 + i,
            ip_addr=f"172.30.0.{69 + i}",
            bootstrap_id=i  # Connect to different bootstrap nodes
        )
        nodes.append(node)
    return nodes

def main():
    """Generate complete 50-node docker-compose configuration."""
    print(HEADER)
    
    # Generate nodes
    print("  # =========================================================================")
    print("  # Bootstrap Nodes (3 nodes) - Network Discovery & DHT")
    print("  # =========================================================================")
    for node in generate_bootstrap_nodes(3):
        print(node)
    
    print("\n  # =========================================================================")
    print("  # Aggregator/Parameter Server Nodes (5 nodes) - ML Coordination")
    print("  # =========================================================================")
    for node in generate_aggregator_nodes(5):
        print(node)
    
    print("\n  # =========================================================================")
    print("  # Worker Nodes (40 nodes) - ML Training Workers")
    print("  # =========================================================================")
    for node in generate_worker_nodes(40):
        print(node)
    
    print("\n  # =========================================================================")
    print("  # GUI Client Nodes (2 nodes) - Testing GUI Functionality")
    print("  # =========================================================================")
    for node in generate_gui_nodes(2):
        print(node)
    
    print(NETWORK_CONFIG)
    
    # Print statistics
    print("\n# Generated configuration:")
    print("#   Bootstrap nodes: 3")
    print("#   Aggregator nodes: 5")
    print("#   Worker nodes: 40")
    print("#   GUI clients: 2")
    print("#   Total: 50 nodes")
    print("#   IP range: 172.30.0.10 - 172.30.0.71")

if __name__ == "__main__":
    main()
